services:
  redis:
    image: redis
  app:
    build: ./
    depends_on:
      - "redis"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
      - JWT_SECRET=not_a_good_secret
    ports: 
      - "8080:8080"
    volumes: 
      - ./:/app